# Generated by Django 4.2.7 on 2024-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='user_account',
            new_name='account',
        ),
        migrations.AddField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(default='example name', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_reason',
            field=models.CharField(verbose_name='Reason for Contacting Us'),
        ),
    ]
