# Generated by Django 4.2 on 2024-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
