# Generated by Django 4.2 on 2024-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_acres',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='has_fellprune',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='has_surface',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
