# Generated by Django 4.2.7 on 2024-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_image_url_remove_service_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
