# Generated by Django 4.2.7 on 2024-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
