# Generated by Django 4.2.7 on 2024-10-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='alt',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
