# Generated by Django 4.2.7 on 2024-09-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_original_bag_order_original_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eircode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
