# Generated by Django 4.2.7 on 2024-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
